photo/urls.py
from django.conf.urls import url
from . import views

app_name = 'photo'

urlpatterns = [
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create_album/$', views.create_album, name='create_album'),
    url(r'^(?P<album_id>[0-9]+)/create_picture/$', views.create_picture, name='create_picture'),
    url(r'^(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
    url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^(?P<album_id>[0-9]+)/favorite_album/$', views.favorite_album, name='favorite_album'),
    url(r'^(?P<album_id>[0-9]+)/delete_pic/(?P<song_id>[0-9]+)/$', views.delete_pic, name='delete_pic'),
    url(r'^$', views.index, name='index'),
    ]

photos/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('photo.urls')),
    url(r'^photo/',include('photo.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
# Create your models here.
class Album(models.Model):
    user = models.ForeignKey(User, default=1)
    album_title = models.CharField(max_length=250)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.album_title

class Picture(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    pic_title = models.CharField(max_length=250)
    pic_file = models.FileField(default='')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.pic_title

photo/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Album, Picture


class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['album_title', 'album_logo']


class PictureForm(forms.ModelForm):

    class Meta:
        model = Picture
        fields = ['pic_title','pic_file']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

photo/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,Http404
from .models import Album,Picture
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from .forms import AlbumForm, PictureForm, UserForm
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.core.urlresolvers import reverse_lazy
from django.http import JsonResponse
# Create your views here.
def index(request):
    if not request.user.is_authenticated():
        return render(request, 'photo/index.html')
    else:
        albums = Album.objects.filter(user=request.user).order_by('-pk')
        picture_results = Picture.objects.all()
        query = request.GET.get("q")
        if query:
            albums = albums.filter(
                Q(album_title__icontains=query)
            ).distinct()
            picture_results = picture_results.filter(
                Q(pic_title__icontains=query)
            ).distinct()
            return render(request, 'photo/index.html', {
                'albums': albums,
                'songs': picture_results,
            })
        else:
            return render(request, 'photo/index.html', {'albums': albums})

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return redirect('/')
            else:
                return render(request, 'photo/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'photo/login.html', {'error_message': 'Invalid login'})
    return render(request, 'photo/login.html')

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return redirect('photo:index')
    context = {
        "form": form,
    }
    return render(request, 'photo/register.html', context)

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return redirect('photo:login_user')

def create_album(request):
    if not request.user.is_authenticated():
        return redirect('photo:login_user')
    else:
        form = AlbumForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            album = form.save(commit=False)
            album.user = request.user
            album.album_logo = request.FILES['album_logo']
            album.save()
            return redirect('photo:detail', album_id=album.id)
        context = {
            "form": form,
        }
        return render(request, 'photo/create_album.html', context)

def detail(request, album_id):
    if not request.user.is_authenticated():
        return redirect('photo:login_user')
    else:
        user = request.user
        album = get_object_or_404(Album, pk=album_id)
        return render(request, 'photo/detail.html', {'album': album, 'user': user})

def create_picture(request, album_id):
    form = PictureForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    if form.is_valid():
        albums_pictures = album.picture_set.all()
        for s in albums_pictures:
            if s.pic_title == form.cleaned_data.get("pic_title"):
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'You already added that picture',
                }
                return render(request, 'photo/create_picture.html', context)
        song = form.save(commit=False)
        song.album = album
        song.save()
        return redirect('photo:detail', album_id=album.id)
    context = {
        'album': album,
        'form': form,
    }
    return render(request, 'photo/create_picture.html', context)

def delete_album(request, album_id):
    album = Album.objects.get(pk=album_id)
    album.delete()
    albums = Album.objects.filter(user=request.user)
    return redirect('/')

def favorite(request, song_id):
    pic = get_object_or_404(Picture, pk=song_id)
    try:
        if pic.is_favorite:
            pic.is_favorite = False
        else:
            pic.is_favorite = True
        pic.save()
    except (KeyError, Picture.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})

def favorite_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        if album.is_favorite:
            album.is_favorite = False
        else:
            album.is_favorite = True
        album.save()
    except (KeyError, Album.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})

def delete_pic(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    song = Picture.objects.get(pk=song_id)
    song.delete()
    return redirect('photo:detail',album_id)

photo/templates/photo/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Pictures{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0-beta.3/cosmo/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'photo/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'photo/js/main.js' %}"></script>
  </head>
<body>
  <nav class="navbar navbar-inverse bg-inverse" role="navigation">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
  <span class="sr-only">Toggle navigation</span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="{% url 'photo:index' %}">Pictures</a>
</div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav">
  <li class="active"><a href="{% url 'photo:index' %}">Home</a></li>
</ul>
<div class="col-sm-3 col-md-3">
    <form class="navbar-form" role="search">
    <div class="input-group">
        <input type="text" class="form-control" placeholder="Search" name="q">
        <div class="input-group-btn">
            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
        </div>
    </div>
    </form>
</div>

<ul class="nav navbar-nav navbar-right">
  {% if user.is_authenticated %}
  <li><a href="{% url 'photo:create_album' %}">Create Album</a></li>
  <li>
    <a href="{% url 'photo:logout_user' %}">Logout</a>
  </li>
  {% else %}
  <li><a href="{% url 'photo:login_user' %}">Login</a></li>
  <li><a href="{% url 'photo:register' %}">Signup</a></li>
  {% endif %}
</ul>
</div><!-- /.navbar-collapse -->
</nav>
          {% block content %}
          {% endblock %}
  </body>
</html>

photo/templates/photo/create_album.html
{% extends 'photo/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block content %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Album</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'photo/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

photo/templates/photo/create_picture.html
{% extends 'photo/base.html' %}
{% block title %}Add a New Picture{% endblock %}

{% block content %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'photo:detail' album.id %}">
                            {% if album.album_logo %}
                                <img src="{{ album.album_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ album.album_title }}</h1>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'photo:index' %}">All Albums</a></li>
                <li role="presentation" class="active"><a href="{% url 'photo:create_picture' album.id %}">Add New Picture</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Picture</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="album" value="{{ album }}">
                        {% include 'photo/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

photo/templates/photo/detail.html
{% extends 'photo/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block content %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'photo:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} </h1>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'photo:index' %}">All Albums</a></li>
                <li role="presentation"><a href="{% url 'photo:create_picture' album.id %}">Add New Photo</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Photos</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                        {% for song in album.picture_set.all %}

                            <div class="col-sm-6 col-lg-3">
                                <div class="thumbnail">
                                    <a href="{ song.pic_file.url }">
                                        <img src="{{ song.pic_file.url }}" class="img-responsive" style="height:200px;width:512px;">
                                    </a>
                                    <div class="caption">
                                        <h2>{{ song.pic_title }}</h2>

                                        <!-- View Details -->
                                        <a target="_blank" href="{{ song.pic_file.url }}" class="btn btn-primary btn-sm" role="button">View</a>
                                        <form action="{% url 'photo:delete_pic' album.id song.id %}" method="post" style="display: inline;">
                                                {% csrf_token %}
                                                <input type="hidden" name="song_id" value="{{ song.id }}" />
                                                <button type="submit" class="btn btn-default btn-sm">
                                                    <span class="glyphicon glyphicon-trash"></span>
                                                </button>
                                            </form>
                                            <a href="{% url 'photo:favorite' song.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                            <span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span>
                                        </a>

                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

photo/templates/photo/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

photo/templates/photo/index.html
{% extends 'photo/base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
<div class="albums-container container-fluid">

    {% if user.is_authenticated %}
    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Albums</h3>
        </div>
        {% if albums %}
            {% for album in albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'photo:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive" style="height:200px;width:512px;">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>

                            <!-- View Details -->
                            <a href="{% url 'photo:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                            <form action="{% url 'photo:delete_album' album.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="album_id" value="{{ album.id }}" />
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>
                                <a href="{% url 'photo:favorite_album' album.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'photo:create_album' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
{% else %}
<div>
<div>
    <div class="ak">
        <h3>What is Pictures?</h3>
        <p>Pictures is an app that allows you to upload and store all of your Pictures on the cloud.</p>
        <h3>How do I add pictures?</h3>
        <p>First, create a new album by filling out the form on this page. Once an album is created you will be able to add/upload songs.</p>
        <h3>What are some Album logo best practices?</h3>
        <ul>
            <li>Have a resolution of 512x512</li>
            <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
            <li>Remain under the 2MB limit.</li>
            <li>Square images look best</li>
        </ul>
    </div>
</div>
</div>
{% endif %}
</div>
{% endblock %}

photo/templates/photo/login.html
{% extends 'photo/base.html' %}
{% block title %}Log In{% endblock %}

{% block content %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'photo:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'photo:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

photo/templates/photo/register.html
{% extends 'photo/base.html' %}
{% block title %}Register{% endblock %}

{% block content %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'photo/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'photo:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}